services:
  chrome-novnc:
    container_name: chrome-novnc
    image: ghcr.nju.edu.cn/al-one/chrome:grass
    ports:
      - "${HOST_PORT-8081}:8080/tcp"
    environment:
      - VNC_PASS=${VNC_PASS-CHANGE_IT}
      - VNC_RESOLUTION=${VNC_RESOLUTION-1440x880}
    restart: unless-stopped
